# Generated by Django 6.0.6 on 2026-06-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donation_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='deliverpic',
            new_name='deliverypic',
        ),
    ]
